#############################################################################
# Makefile for building: ft_gkrellm.app/Contents/MacOS/ft_gkrellm
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  ft_gkrellm.pro
# Template: app
# Command: /nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile ft_gkrellm.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/macx-clang -I. -I/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers -I/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -F/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib
QMAKE         = /nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ft_gkrellm1.0.0
DISTDIR = /Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Rendu/S3/PiscineC++/RUSH/RUSH01/.tmp/ft_gkrellm1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib -lncurses -framework QtWidgets -F/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Qtwindow.cpp moc_Qtwindow.cpp
OBJECTS       = main.o \
		Qtwindow.o \
		moc_Qtwindow.o
DIST          = /Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/qdevice.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/unix.conf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/mac.conf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/macx.conf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/clang.conf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/qconfig.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/qt.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/resources.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/moc.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/uic.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/lex.prf \
		ft_gkrellm.pro Qtwindow.h main.cpp \
		Qtwindow.cpp
QMAKE_TARGET  = ft_gkrellm
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = ft_gkrellm.app/Contents/MacOS/ft_gkrellm

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_qtwindow.h $(OBJECTS)  
	@test -d ft_gkrellm.app/Contents/MacOS/ || mkdir -p ft_gkrellm.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ft_gkrellm.pro /Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf /Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/qdevice.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/unix.conf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/mac.conf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/macx.conf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/clang.conf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/qconfig.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/qt.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/resources.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/moc.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/uic.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/lex.prf \
		ft_gkrellm.pro \
		/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl \
		/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile ft_gkrellm.pro
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/spec_pre.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/qdevice.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/device_config.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/shell-unix.conf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/unix.conf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/mac.conf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/macx.conf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/gcc-base.conf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/clang.conf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/common/clang-mac.conf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/qconfig.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/qt_functions.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/qt_config.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/spec_post.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/default_pre.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/resolve_config.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/default_post.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/warn_on.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/qt.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/resources.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/moc.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/uic.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/unix/thread.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/mac/rez.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/exceptions.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/yacc.prf:
/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/features/lex.prf:
ft_gkrellm.pro:
/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl:
/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile ft_gkrellm.pro

qmake_all: FORCE

ft_gkrellm.app/Contents/PkgInfo: 
	@test -d ft_gkrellm.app/Contents || mkdir -p ft_gkrellm.app/Contents
	@$(DEL_FILE) ft_gkrellm.app/Contents/PkgInfo
	@echo "APPL????" >ft_gkrellm.app/Contents/PkgInfo
ft_gkrellm.app/Contents/Resources/empty.lproj: 
	@test -d ft_gkrellm.app/Contents/Resources || mkdir -p ft_gkrellm.app/Contents/Resources
	@touch ft_gkrellm.app/Contents/Resources/empty.lproj
	
ft_gkrellm.app/Contents/Info.plist: 
	@test -d ft_gkrellm.app/Contents || mkdir -p ft_gkrellm.app/Contents
	@$(DEL_FILE) ft_gkrellm.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.ft_gkrellm,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,ft_gkrellm,g" -e "s,@TYPEINFO@,????,g" /Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/macx-clang/Info.plist.app >ft_gkrellm.app/Contents/Info.plist

all: Makefile \
		ft_gkrellm.app/Contents/PkgInfo \
		ft_gkrellm.app/Contents/Resources/empty.lproj \
		ft_gkrellm.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents Qtwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp Qtwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents qtwindow.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r ft_gkrellm.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_Qtwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Qtwindow.cpp
moc_Qtwindow.cpp: /Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		Qtwindow.h
	/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/mkspecs/macx-clang -I/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Rendu/S3/PiscineC++/RUSH/RUSH01 -I/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib Qtwindow.h -o moc_Qtwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_qtwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_qtwindow.h
ui_qtwindow.h: qtwindow.ui
	/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/bin/uic qtwindow.ui -o ui_qtwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp Qtwindow.h \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLineEdit \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QProgressBar \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressbar.h \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSlider \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qslider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Qtwindow.o: Qtwindow.cpp Qtwindow.h \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Volumes/Data/nfs/zfs-student-2/users/2013/gpetrov/Applications/Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		ui_qtwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Qtwindow.o Qtwindow.cpp

moc_Qtwindow.o: moc_Qtwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Qtwindow.o moc_Qtwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

